name: Atualizar Última Música do YouTube

on:
  schedule:
    - cron: '*/10 * * * *'  # Roda a cada 10 minutos
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install google-api-python-client
          pip install google-auth google-auth-oauthlib google-auth-httplib2 requests flask selenium html2image
          pip install webdriver_manager  # Instala o webdriver_manager

      - name: Rodar script Python para atualizar o index.html
        run: python yt-music-on-git.py
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Atualizando index.html com a última música do YouTube"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
